{% set name = "sinfo" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sinfo-{{ version }}.tar.gz
  sha256: 81ea91c69a875de178e10bada9476d7300a1f712e1823dbd7714f43a10baba4d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - stdlib-list
    - colorama

test:
  imports:
    - sinfo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/joelostblom/sinfo
  summary: sinfo outputs version information for modules loaded in the current session, Python, and the OS.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pinin4fjords
